import {Platform, StyleSheet} from 'react-native';
import {scale, moderateScale} from 'react-native-size-matters';

const styles = StyleSheet.create({
  appButtonText: {
    fontSize: moderateScale(18),
    color: '#fff',
    fontWeight: 'bold',
    alignSelf: 'center',
    textTransform: 'uppercase',
  },
  mainContainer: {
    flex: 1,
    // flexGrow: 3,
    // justifyContent: 'center',
    // color: 'black',
    flexDirection: 'row',
    // alignContent: 'center',
    // justifyContent: 'space-between',
    // backgroundColor: 'green',
    // width: moderateScale(110),
    padding: moderateScale(4),
  },
  TableTitleContainer: {
    flex: 3,
    // backgroundColor: 'blue',
    flexDirection: 'row',
    // marginHorizontal: 8,
    // height: moderateScale(70),
  },
  TableStatusContainer: {
    flex: 2,
    // backgroundColor: 'darkorange',
    flexDirection: 'row',
    // marginHorizontal: 8,
    // height: moderateScale(70),
  },
  TableButtonsContainer: {
    flex: 3,
    // backgroundColor: 'blue',
    flexDirection: 'row',
    // marginHorizontal: 8,
    // height: moderateScale(70),
  },
  TableButtonContainer: {
    height: moderateScale(56),
    width: moderateScale(94),
    marginHorizontal: 16,
    paddingVertical: 18,
    // backgroundColor: 'red',
  },
  TableItemContainer: {
    marginHorizontal: 16,
  },

  rightContainer: {
    color: 'black',
    flexDirection: 'row',
    marginBottom: 20,
    justifyContent: 'center',
    alignSelf: 'flex-end',
    alignItems: 'flex-end',
    alignContent: 'flex-end',
  },
  checkboxContainer: {
    color: 'black',
    flexDirection: 'row',
    marginBottom: 20,
    alignContent: 'flex-start',
  },
  label: {
    fontFamily: Platform.OS === 'ios' ? 'Bebas Neue Pro' : 'bebasneuepro',
    alignSelf: 'flex-start',
    fontWeight: '600',
    fontSize: moderateScale(18),
    margin: 8,
    color: 'black',
  },
  dollarSign: {
    fontFamily: Platform.OS === 'ios' ? 'Bebas Neue Pro' : 'bebasneuepro',
    alignSelf: 'flex-start',
    fontSize: moderateScale(16),
    marginTop: moderateScale(4),
    marginLeft: moderateScale(4),
    marginRight: moderateScale(2),
    color: 'black',
  },
  icon: {
    fontSize: moderateScale(16),
    marginTop: moderateScale(8),
    marginBottom: moderateScale(4),
    marginRight: moderateScale(4),
    color: '#F26F21',
  },
  labelCost: {
    fontFamily: Platform.OS === 'ios' ? 'Bebas Neue Pro' : 'bebasneuepro',
    alignSelf: 'flex-start',
    fontWeight: '500',
    fontSize: moderateScale(18),
    marginTop: moderateScale(8),
    marginBottom: moderateScale(4),
    marginRight: moderateScale(4),
    color: 'black',
  },
  mainCellContainer: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#ffff',
    elevation: 4,
    borderRadius: moderateScale(2),
    margin: moderateScale(4),
  },
  bottomCellContainer: {
    width: '100%',
    flexDirection: 'row',
    elevation: 10,
    alignContent: 'flex-start',
    alignSelf: 'flex-start',
    margin: moderateScale(8),
  },
  bgImg: {
    flexDirection: 'column',
    justifyContent: 'flex-end',
    backgroundColor: '#ffff',
    alignContent: 'flex-end',
    alignItems: 'flex-end',
    alignSelf: 'flex-end',
    overflow: 'hidden',
    borderRadius: scale(4),
    resizeMode: 'cover',
  },
  TitleText: {
    textTransform: 'uppercase',
    fontFamily: Platform.OS === 'ios' ? 'Bebas Neue Pro' : 'bebasneuepro',
    elevation: 10,
    alignContent: 'flex-end',
    alignSelf: 'baseline',
    fontSize: scale(12),
    marginHorizontal: moderateScale(8),
    marginVertical: moderateScale(4),
    color: 'white',
  },
  Icon: {
    elevation: 10,
    alignContent: 'flex-end',
    alignSelf: 'baseline',
    fontSize: scale(16),
    marginHorizontal: moderateScale(8),
    marginVertical: moderateScale(4),
    color: 'white',
  },
  TableItemText: {
    fontFamily: Platform.OS === 'ios' ? 'Bebas Neue Pro' : 'bebasneuepro',
    fontSize: moderateScale(14),
    textAlign: 'left',
    marginVertical: moderateScale(8),
    marginHorizontal: moderateScale(8),
    fontWeight: '600',
    alignItems: 'center',
    alignContent: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
    color: 'black',
    // backgroundColor: 'yellow',
  },
});

export default styles;
