import {Platform, StyleSheet} from 'react-native';
import {scale, moderateScale} from 'react-native-size-matters';

const styles = StyleSheet.create({
  imageThumbnail: {
    justifyContent: 'center',
    alignItems: 'center',
    height: 90,
    // width: 90,
  },
  appButtonText: {
    fontSize: moderateScale(18),
    color: '#fff',
    fontWeight: 'bold',
    alignSelf: 'center',
    textTransform: 'uppercase',
  },
  modalContainer: {
    // borderColor: 'grey',
    // borderBottomWidth: 0.194,
    // color: 'black',
    flexDirection: 'column',
    // marginBottom: 20,
    alignContent: 'center',
    // justifyContent: 'space-between',
  },
  mainContainer: {
    color: 'black',
    flexDirection: 'row',
    // marginBottom: 20,
    // alignContent: 'center',
    padding: moderateScale(8),
    justifyContent: 'space-between',
  },
  rightContainer: {
    color: 'black',
    flexDirection: 'row',
    // marginBottom: 20,
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    alignContent: 'flex-end',
  },
  checkboxContainer: {
    color: 'black',
    flexDirection: 'row',
    padding: moderateScale(5),

    alignContent: 'flex-start',
  },
  label: {
    fontFamily: Platform.OS === 'ios' ? 'Bebas Neue Pro' : 'bebasneuepro',
    alignSelf: 'flex-start',
    fontWeight: '600',
    fontSize: moderateScale(20),
    padding: 8,

    color: 'black',
  },
  labelPop: {
    // fontFamily: Platform.OS === 'ios' ? 'Bebas Neue Pro' : 'bebasneuepro',
    // alignSelf: 'flex-start',
    // fontWeight: '600',
    // fontSize: moderateScale(18),
    margin: 0,
    // color: 'black',
  },
  dollarSign: {
    fontFamily: Platform.OS === 'ios' ? 'Bebas Neue Pro' : 'bebasneuepro',
    alignSelf: 'flex-start',
    fontSize: moderateScale(18),
    marginTop: moderateScale(4),
    marginLeft: moderateScale(4),
    marginRight: moderateScale(2),
    color: 'black',
  },
  icon: {
    fontSize: moderateScale(16),
    marginTop: moderateScale(8),
    marginBottom: moderateScale(4),
    marginRight: moderateScale(4),
    // color: '#F26F21',
  },
  labelCost: {
    fontFamily: Platform.OS === 'ios' ? 'Bebas Neue Pro' : 'bebasneuepro',
    alignSelf: 'flex-start',
    fontWeight: '500',
    fontSize: moderateScale(16),
    marginTop: moderateScale(8),
    marginBottom: moderateScale(4),
    marginRight: moderateScale(4),
    color: 'black',
  },
  mainCellContainer: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#ffff',
    elevation: 4,
    borderRadius: moderateScale(2),
    margin: moderateScale(4),
  },
  bottomCellContainer: {
    width: '100%',
    flexDirection: 'row',
    elevation: 10,
    alignContent: 'flex-start',
    alignSelf: 'flex-start',
    margin: moderateScale(8),
  },
  bgImg: {
    flexDirection: 'column',
    justifyContent: 'flex-end',
    backgroundColor: '#ffff',
    alignContent: 'flex-end',
    alignItems: 'flex-end',
    alignSelf: 'flex-end',
    overflow: 'hidden',
    borderRadius: scale(4),
    resizeMode: 'cover',
  },
  TitleText: {
    textTransform: 'uppercase',
    fontFamily: Platform.OS === 'ios' ? 'Bebas Neue Pro' : 'bebasneuepro',
    elevation: 10,
    alignContent: 'flex-end',
    alignSelf: 'baseline',
    fontSize: scale(12),
    marginHorizontal: moderateScale(8),
    marginVertical: moderateScale(4),
    color: 'white',
  },
  Icon: {
    elevation: 10,
    alignContent: 'flex-end',
    alignSelf: 'baseline',
    fontSize: scale(16),
    marginHorizontal: moderateScale(8),
    marginVertical: moderateScale(4),
    color: 'white',
  },
  virtualTwilightContainer: {
    margin: 8,
    backgroundColor: 'grey',
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    alignContent: 'center',
  },
  virtualTwilightVideoContainer: {
    padding: moderateScale(16),
    // backgroundColor: 'grey',
    // height: moderateScale(50),
    // width: moderateScale(190),
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    alignContent: 'center',
  },
  counterContainer: {
    flexDirection: 'row',
    // marginTop: moderateScale(-32),
    // marginHorizontal: moderateScale(2),
    // paddingHorizontal: moderateScale(8),
    justifyContent: 'space-evenly',
    // backgroundColor:"black",
    // backgroundColor:"tranceparent",
  },
  counterBtnContainer: {
    flexDirection: 'row',
    marginTop: moderateScale(0),
    marginHorizontal: moderateScale(2),
    paddingHorizontal: moderateScale(8),
    justifyContent: 'space-evenly',
    // backgroundColor:"black",
    // backgroundColor:"tranceparent",
  },
  textCounter: {
    fontFamily: Platform.OS === 'ios' ? 'Bebas Neue Pro' : 'bebasneuepro',
    fontSize: moderateScale(24),
    alignSelf: 'center',
    marginLeft: moderateScale(0),
    // marginTop: moderateScale(12),
    // marginBottom: moderateScale(14),
    color: 'black',
  },
  textCounterNum: {
    fontFamily: Platform.OS === 'ios' ? 'Bebas Neue Pro' : 'bebasneuepro',
    fontSize: moderateScale(18),
    alignSelf: 'center',
    paddingHorizontal: moderateScale(4),
    // marginTop: moderateScale(12),
    // marginBottom: moderateScale(14),
    color: 'black',
    borderColor: 'black',
    borderWidth: moderateScale(1),
  },
});

export default styles;
