import {Platform, StyleSheet} from 'react-native';
import {scale, moderateScale} from 'react-native-size-matters';
import useTheme from '../../theme/useTheme';

const {colors} = useTheme;
const styles = StyleSheet.create({
  appButtonText: {
    fontSize: moderateScale(18),
    color: '#fff',
    fontWeight: 'bold',
    alignSelf: 'center',
    textTransform: 'uppercase',
  },
  mainContainer: {
    borderColor: 'grey',
    borderBottomWidth: 0.194,
    color: 'black',
    flexDirection: 'row',
    marginBottom: moderateScale(4),
    alignContent: 'center',
    justifyContent: 'space-evenly',
    width: moderateScale(300),
    // backgroundColor: 'blue',
  },
  leftContainer: {
    color: 'black',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignSelf: 'flex-start',
    alignItems: 'flex-start',
    alignContent: 'flex-start',
    width: moderateScale(150),
    // backgroundColor: 'red',
  },
  middleContainer: {
    color: 'black',
    flexDirection: 'row',
    justifyContent: 'center',
    alignSelf: 'flex-start',
    alignItems: 'flex-start',
    alignContent: 'flex-start',
    width: moderateScale(50),
    paddingTop: moderateScale(8),
    // backgroundColor: 'red',
  },
  rightContainer: {
    color: 'black',
    flexDirection: 'row',
    marginBottom: 20,
    justifyContent: 'center',
    alignSelf: 'flex-end',
    alignItems: 'flex-end',
    alignContent: 'flex-end',
    // backgroundColor: 'red',
    width: moderateScale(100),
  },
  checkboxContainer: {
    color: 'black',
    flexDirection: 'row',
    marginBottom: 4,
    alignContent: 'flex-start',
  },
  label: {
    alignSelf: 'flex-start',
    fontWeight: '600',
    margin: 8,

    fontFamily: Platform.OS === 'ios' ? 'Bebas Neue Pro' : 'bebasneuepro',
    fontSize: scale(16),
    color: 'gray',
  },
  dollarSign: {
    fontFamily: Platform.OS === 'ios' ? 'Bebas Neue Pro' : 'bebasneuepro',
    alignSelf: 'flex-start',
    fontSize: moderateScale(16),
    marginTop: moderateScale(4),
    marginLeft: moderateScale(4),
    marginRight: moderateScale(2),
    color: 'black',
  },
  icon: {
    fontSize: moderateScale(16),
    marginTop: moderateScale(8),
    marginBottom: moderateScale(4),
    marginRight: moderateScale(4),
    color: '#F26F21',
  },
  labelCost: {
    marginTop: moderateScale(8),
    marginBottom: moderateScale(4),
    marginRight: moderateScale(4),
    marginLeft: moderateScale(16),
    alignSelf: 'flex-start',
    fontWeight: '600',
    margin: 8,
    fontFamily: Platform.OS === 'ios' ? 'Bebas Neue Pro' : 'bebasneuepro',
    fontSize: scale(14),
    color: colors.SplashButtonBluecolor,
    textAlign: 'left',
    textDecorationLine: 'underline',
  },

  bgImg: {
    flexDirection: 'column',
    justifyContent: 'flex-end',
    backgroundColor: '#ffff',
    alignContent: 'flex-end',
    alignItems: 'flex-end',
    alignSelf: 'flex-end',
    overflow: 'hidden',
    borderRadius: scale(4),
    resizeMode: 'cover',
  },
  TitleText: {
    textTransform: 'uppercase',
    fontFamily: Platform.OS === 'ios' ? 'Bebas Neue Pro' : 'bebasneuepro',
    elevation: 10,
    alignContent: 'flex-end',
    alignSelf: 'baseline',
    fontSize: scale(12),
    marginHorizontal: moderateScale(8),
    marginVertical: moderateScale(4),
    color: 'white',
  },
  Icon: {
    elevation: 10,
    alignContent: 'flex-end',
    alignSelf: 'baseline',
    fontSize: scale(16),
    marginHorizontal: moderateScale(8),
    marginVertical: moderateScale(4),
    color: 'white',
  },
});

export default styles;
