import {Platform, StyleSheet} from 'react-native';
import {scale, moderateScale, verticalScale} from 'react-native-size-matters';
import useTheme from '../../theme/useTheme';

const {colors} = useTheme;
const styles = StyleSheet.create({
  home: {
    alignItems: 'center',
    alignContent: 'center',
    alignSelf: 'stretch',
    paddingTop: moderateScale(4),
    height: '100%',
    width: '100%',
    backgroundColor: '#fff',
  },
  GridViewContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    padding: moderateScale(2),
    margin: moderateScale(8),
    alignSelf: 'center',
  },
  textLogo: {
    alignItems: 'center',
    alignSelf: 'center',
    width: scale(191.19),
    marginTop: moderateScale(64),
    marginHorizontal: moderateScale(24),
    height: verticalScale(28.47),
    resizeMode: 'contain',
  },
  imageLogo: {
    marginTop: moderateScale(32),
    alignItems: 'center',
    alignSelf: 'center',
    width: scale(191.19),
    marginHorizontal: moderateScale(24),
    height: verticalScale(152.78),
    resizeMode: 'contain',
  },
  SearchBarContainer: {
    marginTop: moderateScale(8),
    justifyContent: 'center',
    alignItems: 'center',
    padding: moderateScale(2),
    marginLeft: moderateScale(8),
    marginRight: moderateScale(8),
    height: verticalScale(40),
    width: scale(316),
    alignSelf: 'center',
    elevation: 0,
  },
  HeaderContainer: {
    // flexDirection: 'row',
    // flexWrap: 'wrap',
    alignItems: 'center',
    alignContent: 'center',
    textAlign: 'center',
    paddingTop: moderateScale(4),
    // paddingBottom: moderateScale(16),
    marginTop: moderateScale(16),
    // marginBottom: moderateScale(16),
    marginHorizontal: moderateScale(16),
    // backgroundColor: 'green',
  },
  scrollView: {
    marginHorizontal: moderateScale(2),
  },
  BodyContainer: {
    alignSelf: 'center',
    alignContent: 'center',
    alignItems: 'center',
    // marginTop: moderateScale(32),
    paddingBottom: moderateScale(16),
    // marginHorizontal: moderateScale(4),
    // backgroundColor: 'yellow',
  },
  SectionContainer: {
    alignSelf: 'center',
    alignContent: 'center',
    alignItems: 'center',
    marginVertical: moderateScale(8),
    marginHorizontal: moderateScale(14),
    height: moderateScale(250),
    // elevation: 10,
    // backgroundColor: 'blue',
  },
  avatar: {
    width: 160,
    height: 160,
    borderRadius: 83,
    // color: 'white',
    marginBottom: 64,
    // backgroundColor: 'red',
    // padding: moderateScale(8),
    alignSelf: 'center',
    // position: 'absolute',
    marginTop: 0,
    marginLeft: 8,
    // backgroundColor: 'blue',
  },
  logo: {
    width: moderateScale(290),
    height: moderateScale(242),
    borderRadius: 0,
    borderWidth: 0,
    borderColor: 'white',
    // marginBottom: 64,
    // marginLeft: 32,
    alignSelf: 'flex-start',
    // position: 'absolute',
    resizeMode: 'contain',
    // top: 0,
    bottom: 0,
    left: 0,
  },
  iteml: {
    resizeMode: 'cover',
    width: '50%',
    alignItems: 'center',
    paddingLeft: 8,
  },
  itemr: {
    paddingTop: moderateScale(24),
    // paddingLeft: moderateScale(24),
    // resizeMode: 'cover',
    alignContent: 'flex-start',
    alignItems: 'flex-start',
    alignSelf: 'flex-start',
    justifyContent: 'flex-start',
    width: '50%',
    textAlign: 'left',
    // backgroundColor: 'yellow',
  },
  pageText: {
    // fontFamily: 'Bebas Neue Pro',

    fontFamily: Platform.OS === 'ios' ? 'Bebas Neue Pro' : 'bebasneuepro',
    elevation: 10,
    alignSelf: 'center',
    textAlign: 'left',
    color: '#0E74BE',
    textTransform: 'uppercase',
    fontSize: scale(22),
    marginTop: Platform.OS === 'ios' ? moderateScale(32) : moderateScale(16),
  },
  HeaderText: {
    // fontFamily: 'Bebas Neue Pro',

    fontFamily: Platform.OS === 'ios' ? 'Bebas Neue Pro' : 'bebasneuepro',
    elevation: 10,
    alignSelf: 'flex-start',
    textAlign: 'left',
    color: '#000',
    letterSpacing: moderateScale(1.2),
    textTransform: 'uppercase',
    fontWeight: '600',
    fontSize: scale(46),
  },
  SubHeaderText: {
    // fontFamily: 'Bebas Neue Pro',

    fontFamily: Platform.OS === 'ios' ? 'Bebas Neue Pro' : 'bebasneuepro',
    elevation: 10,
    alignSelf: 'center',
    fontWeight: '400',
    letterSpacing: moderateScale(1.2),
    color: '#707070',
    fontSize: scale(24),
  },
  LoginButtonContainer: {
    marginTop: moderateScale(84),
    justifyContent: 'center',
    alignItems: 'center',
    // padding: moderateScale(2),
    height: verticalScale(64),
    width: scale(188),
    alignSelf: 'center',
  },
  SectionHeaderText: {
    alignContent: 'flex-start',
    textAlign: 'left',
    fontFamily: 'Bebas Neue Pro',
    color: '#0E74BE',
    fontSize: scale(14),
    textTransform: 'uppercase',
    marginVertical: moderateScale(8),
  },
  container: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: 'white',
    height: scale(96),
  },
  child: {width: '100%', justifyContent: 'center', height: scale(64)},
});
export default styles;
