import {Platform, StyleSheet} from 'react-native';
import {moderateScale, scale, verticalScale} from 'react-native-size-matters';

const styles = StyleSheet.create({
  ButtonContainer: {
    marginTop: moderateScale(24),
    justifyContent: 'center',
    alignItems: 'center',
    padding: moderateScale(2),
    marginLeft: moderateScale(8),
    marginRight: moderateScale(8),
    height: verticalScale(64),
    width: scale(208),
    alignSelf: 'center',
    // backgroundColor: 'red',
  },
  Icon: {
    elevation: 10,
    alignContent: 'flex-end',
    alignSelf: 'baseline',
    fontSize: scale(56),
    marginLeft: moderateScale(20),
    marginVertical: moderateScale(4),
    color: 'black',
  },
  IconSmall: {
    elevation: 10,
    alignContent: 'flex-end',
    alignSelf: 'baseline',
    fontSize: scale(16),
    marginTop: moderateScale(6),
    color: 'green',
  },
  CustomNumberText: {
    fontFamily: Platform.OS === 'ios' ? 'Bebas Neue Pro' : 'bebasneuepro',
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'auto',
    padding: moderateScale(4),
    alignSelf: 'center',
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 16,
  },
  SubTitleText: {
    fontFamily: Platform.OS === 'ios' ? 'Bebas Neue Pro' : 'bebasneuepro',
    elevation: 10,
    color: 'black',
    alignSelf: 'center',
    fontSize: scale(64),
  },

  SubTitleDollarText: {
    fontFamily: Platform.OS === 'ios' ? 'Bebas Neue Pro' : 'bebasneuepro',
    elevation: 10,
    color: 'black',
    alignSelf: 'flex-start',
    fontSize: scale(40),
  },
  DiscountText: {
    fontFamily: Platform.OS === 'ios' ? 'Bebas Neue Pro' : 'bebasneuepro',
    elevation: 10,
    alignSelf: 'center',
    fontSize: scale(18),
    marginRight: moderateScale(8),
    color: 'green',
  },
  DiscText: {
    color: '#707070',
    fontFamily: Platform.OS === 'ios' ? 'Bebas Neue Pro' : 'bebasneuepro',
    elevation: 10,
    alignSelf: 'center',
    fontSize: scale(18),
    paddingVertical: moderateScale(16),
    margin: moderateScale(8),
    textAlign: 'center',
    justifyContent: 'space-evenly',
  },
  DiscText1: {
    color: '#707070',
    fontFamily: Platform.OS === 'ios' ? 'Bebas Neue Pro' : 'bebasneuepro',
    elevation: 10,
    alignSelf: 'center',
    fontSize: scale(21),
    textAlign: 'center',
    justifyContent: 'space-evenly',
  },
  TitleText: {
    fontFamily: Platform.OS === 'ios' ? 'Bebas Neue Pro' : 'bebasneuepro',
    elevation: 10,
    alignSelf: 'center',
    fontSize: scale(25),
  },
  HeaderContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    alignSelf: 'center',
    marginVertical: moderateScale(16),
    marginHorizontal: moderateScale(4),
  },
  scrollView: {
    marginHorizontal: moderateScale(2),
  },
  BodyContainer: {
    alignSelf: 'flex-start',
    alignItems: 'flex-start',
    marginVertical: moderateScale(16),
    marginHorizontal: moderateScale(4),
  },
  SectionContainer: {
    alignItems: 'flex-start',
    marginVertical: moderateScale(12),
    marginHorizontal: moderateScale(24),
  },
  subSectionContainer: {
    flexDirection: 'row',
    marginVertical: moderateScale(12),
    marginHorizontal: moderateScale(56),
  },
  textl: {
    resizeMode: 'cover',
    width: '50%',
    alignItems: 'center',
  },
  textr: {
    resizeMode: 'cover',
    alignContent: 'center',
    width: '50%',
  },
  iteml: {
    resizeMode: 'cover',
    width: '25%',
    alignItems: 'center',
  },
  itemr: {
    resizeMode: 'cover',
    alignContent: 'center',
    width: '75%',
  },
  mainCellContainer: {
    backgroundColor: 'white',
    // paddingHorizontal: scale(18),
    paddingVertical: verticalScale(14),
    borderWidth: moderateScale(1),
    marginHorizontal: moderateScale(16),
    marginVertical: moderateScale(17),
    shadowOffset: {width: 2, height: 8},
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 2,
    borderRadius: moderateScale(2),
  },
  CustomButtonContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    padding: moderateScale(2),
    margin: moderateScale(8),
    height: verticalScale(128),
    width: moderateScale(128),
    alignSelf: 'center',
    backgroundColor: '#ffff',
    elevation: 8,
    shadowColor: 'black',
    shadowOpacity: 0.3,
    shadowOffset: {
      width: moderateScale(2),
      height: moderateScale(2),
    },
    shadowRadius: 5,
  },
  CustomButtonText: {
    fontFamily: Platform.OS === 'ios' ? 'Bebas Neue Pro' : 'bebasneuepro',
    justifyContent: 'center',
    alignItems: 'center',
    padding: moderateScale(2),
    marginTop: moderateScale(8),
    alignSelf: 'center',
    color: '#CCCBCB',
    fontWeight: 'bold',
    fontSize: moderateScale(16),
  },
  list: {
    justifyContent: 'center',
    alignSelf: 'center',
    backgroundColor: 'white',
    height: verticalScale(128),
    width: moderateScale(228),
  },
});
export default styles;
