import { StyleSheet } from "react-native";
import { moderateScale, scale, verticalScale } from "react-native-size-matters";

const styles = StyleSheet.create({
  bgImg: {
    flexDirection: "column",
    justifyContent: "flex-end",
    backgroundColor: "#ffff",
    alignContent: "flex-end",
    alignItems: "flex-end",
    alignSelf: "flex-end",
    overflow: "hidden",
    borderRadius: scale(4),
    resizeMode: "cover",
  },
  bottomCellContainer: {
    width: "100%",
    flexDirection: "row",
    elevation: 10,
    alignContent: "flex-start",
    alignSelf: "flex-start",
    margin: moderateScale(8),
  },
  ButtonContainer: {
    marginTop: moderateScale(64),
    justifyContent: "center",
    alignItems: "center",
    padding: moderateScale(2),
    marginLeft: moderateScale(8),
    marginRight: moderateScale(8),
    height: verticalScale(64),
    width: scale(128),
    alignSelf: "center",
  },
  Icon: {
    elevation: 10,
    alignContent: "flex-end",
    alignSelf: "baseline",
    fontSize: scale(56),
    marginLeft: moderateScale(20),
    marginVertical: moderateScale(4),
    color: "black",
  },
  CustomNumberText: {
    justifyContent: "center",
    alignItems: "center",
    textAlign: "auto",
    padding: moderateScale(4),
    alignSelf: "center",
    color: "#FFFFFF",
    fontWeight: "bold",
    fontSize: 16,
  },
  SubTitleText: {
    fontFamily: "BebasNeuePro-Bold",
    elevation: 10,
    alignSelf: "center",
    fontSize: scale(64),
  },
  DiscountText: {
    fontFamily: "BebasNeuePro-Bold",
    elevation: 10,
    alignSelf: "center",
    fontSize: scale(18),
    color: "green",
  },
  DiscText: {
    fontFamily: "BebasNeuePro-Bold",
    elevation: 10,
    alignSelf: "center",
    fontSize: scale(12),
    paddingVertical: moderateScale(16),
    margin: moderateScale(8),
  },
  TitleText: {
    fontFamily: "BebasNeuePro-Bold",
    elevation: 10,
    alignSelf: "center",
    fontSize: scale(24),
  },
  HeaderContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "flex-start",
    marginVertical: moderateScale(16),
    marginHorizontal: moderateScale(4),
  },
  scrollView: {
    marginHorizontal: moderateScale(2),
  },
  BodyContainer: {
    alignSelf: "flex-start",
    alignItems: "flex-start",
    marginVertical: moderateScale(16),
    marginHorizontal: moderateScale(4),
  },
  SectionContainer: {
    alignItems: "flex-start",
    marginVertical: moderateScale(12),
    marginHorizontal: moderateScale(24),
  },
  subSectionContainer: {
    flexDirection: "row",
    marginVertical: moderateScale(12),
    marginHorizontal: moderateScale(56),
  },
  textl: {
    resizeMode: "cover",
    width: "50%",
    alignItems: "center",
  },
  textr: {
    resizeMode: "cover",
    alignContent: "center",
    width: "50%",
  },
  iteml: {
    resizeMode: "cover",
    width: "25%",
    alignItems: "center",
  },
  itemr: {
    resizeMode: "cover",
    alignContent: "center",
    width: "75%",
  },
  mainCellContainer: {
    elevation: 0.5,
    paddingHorizontal: scale(18),
    paddingVertical: verticalScale(12),
    borderRadius: moderateScale(2),
    borderWidth: moderateScale(1),
    margin: moderateScale(8),
  },
  CustomButtonContainer: {
    justifyContent: "center",
    alignItems: "center",
    padding: moderateScale(2),
    margin: moderateScale(8),
    height: verticalScale(128),
    width: moderateScale(128),
    alignSelf: "center",
    backgroundColor: "#ffff",
    elevation: 8,
    shadowColor: "black",
    shadowOpacity: 0.3,
    shadowOffset: {
      width: moderateScale(2),
      height: moderateScale(2),
    },
    shadowRadius: 5,
  },
  CustomButtonText: {
    fontFamily: "BebasNeuePro-Regular",
    justifyContent: "center",
    alignItems: "center",
    padding: moderateScale(2),
    marginTop: moderateScale(8),
    alignSelf: "center",
    color: "#CCCBCB",
    fontWeight: "bold",
    fontSize: moderateScale(16),
  },
});
export default styles;
